version: "3.8"

services:
  app:
    build:
      context: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: travelexperts
    depends_on:
      - db
    command: npm start

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: travelexperts
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d

  # newman:
  #   image: postman/newman:alpine
  #   container_name: postman_newman
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./tests/postman:/etc/newman
  #   entrypoint:
  #     [
  #       "newman",
  #       "run",
  #       "/etc/newman/travel-experts-backend.postman_collection.json",
  #     ]
